### ISSUE TITLE
Parser review

### ISSUE THREAD

**Issue by SupperZum** [greedy-dev/uri_parser_gdv#1]
Для прохідного:
✔️ ! Brief Description
✔️ ! Project Name
✔️ ! Grammar Rules
❌ ! Unit Tests (res.is_ok() не є нормальним способом перевіряти результат, подивіться як на практичних ми тестували парсер)
✔️ ! Test Coverage
✔️ ! Core Files
✔️ ! CLI

Для максимального:
❌ Error Handling
❌ cargo fmt
❌ cargo clippy
❌ makefile
❌ Completeness
❌ Including a diagram or grammar in the Readme.md
❌ Documentation
✔️ Publishing

❌ Курсова може бути зарахована
Бал: 8/20

**Comment by greedy-dev** [comment]
Fulfilled requirements
- Fixed tests
- Ran `cargo fmt`
- Ran `cargo clippy`
- Added `Makefile`
- Included diagram in the `README.md`
